### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-do#7]
Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

This is part of the GoLive activities.

**Comment by Kannan-CM** [comment]
OneTrust Script for DO:


<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="a25909c9-ce8e-41a5-ba08-af2ebf1840c3" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Cookie Settings</button>

**Comment by Kannan-CM** [comment]
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="59ab66e3-097d-4d0f-8fdb-b4502c87bf88" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Cookie Settings</button>

**Comment by jonatan-lledo-netcentric** [comment]
@Kannan-CM please, there are 2 different IDs for OneTrust. Which one of them is correct?

**Comment by Gonzalo-CG** [comment]
@jonatan-lledo-netcentric confirmed by @Kannan-CM that we need to use the 1st code provided.
